shallow_clone: true

os:
  - Visual Studio 2015

platform: x64
  - x64

branches:
  only:
    - master

install:
  - cinst cmake
  - set PATH=C:\Program Files\CMake\bin;%PATH%

build:
  verbosity: detailed

configuration:
  - Debug

build_script:
  - mkdir build32
  - cd build32
  - cmake .. -G "Visual Studio 14 2015"
  - cmake --build .
  - cd ..
  - mkdir build64
  - cd build64
  - cmake .. -G "Visual Studio 14 2015 Win64"
  - cmake --build .
  - cd ..

test_script:
  - mkdir "C:\tests"
  - cd build32
  - cp "tests\test_case1\Debug\test_case1.exe" "C:\tests\test_case1.exe"
  - ctest -V
  - cd ..
  - cd build64
  - cp "tests\test_case1\Debug\test_case1.exe" "C:\tests\test_case1.exe"
  - cp "..\tests\test_case2\payload.dll" "C:\tests\payload.dll"
  - ctest -V
  